_

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -12,23 +12,22 @@ strategy:
   matrix:
     linux:
       imageName: 'ubuntu-16.04'
-      NIM_COMPILE_TO_CPP: 'false'
+      # NIM_COMPILE_TO_CPP: 'false'
 
     mac:
       imageName: 'macos-10.13'
       NIM_COMPILE_TO_CPP: 'false'
 
     mac_cpp:
+      # 'macos-10.14' fails
       imageName: 'macos-10.13'
       NIM_COMPILE_TO_CPP: 'true'
 
-      # imageName: 'macos-10.14' # fails
     # windows:
     #   imageName: 'vs2017-win2016' # CHECKME
 
 pool:
   vmImage: $(imageName)
-  # vmImage: 'Ubuntu-16.04'
 
 variables:
   MY_VAR: my value
@@ -37,7 +36,7 @@ steps:
 - script: |
     # echo See https://aka.ms/yaml
     # separate step so we can download its log separately (can't download log before a script finishes apparently?)
-
+    set -e
     echo pwd:$(pwd)
     echo NIM_COMPILE_TO_CPP:$NIM_COMPILE_TO_CPP
     echo imageName1:$(imageName)
