try removing manual pinning

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -56,52 +56,14 @@ jobs:
         set -e
         . ci/funs.sh
         echo_run sudo dpkg --add-architecture i386
-        export DEBIAN_FRONTEND='noninteractive'
-
-        # Downgrade llvm:
-        # - llvm has to be downgraded to have 32bit version installed for sfml.
-
-        cat << EOF | sudo tee /etc/apt/preferences.d/pin-to-rel
-        Package: libllvm6.0
-        Pin: origin "azure.archive.ubuntu.com"
-        Pin-Priority: 1001
-        EOF
-
         # echo_run sudo apt-fast update -qq
-        echo_run sudo apt-fast update || echo "failed, see bug #17343"
-        # echo_run sudo apt-fast update -qq || echo "failed, see bug #17343"
+        echo_run sudo apt-fast update -qq || echo "failed, see bug #17343"
         # `:i386` (e.g. in `libffi-dev:i386`) is needed otherwise you may get:
         # `could not load: libffi.so` during dynamic loading.
-
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y gcc-multilib
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y g++-multilib
-
-        # libcurl4-openssl-dev:i386 : Depends: libcurl4:i386 (= 7.58.0-2ubuntu3.12) but it is not going to be installed
-        # libcurl4:i386 : Depends: libssl1.1:i386 (>= 1.1.1) but it is not going to be installed
-        #echo_run sudo apt-get install --allow-downgrades -y libcurl4 libcurl4:i386
-        #echo_run sudo apt-get install --allow-downgrades -y libcurl4-openssl-dev libcurl4-openssl-dev:i386
-
-        # libcurl4:i386 : Depends: libssl1.1:i386 (>= 1.1.1) but it is not going to be installed
-
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y libssl1.1 libssl1.1:i386
-
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y libcurl4 libcurl4:i386
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y libcurl4-openssl-dev libcurl4-openssl-dev:i386
-
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y libgc-dev libgc-dev:i386
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y libsdl1.2-dev libsdl1.2-dev:i386
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y libsfml-dev libsfml-dev:i386
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y libglib2.0-dev libglib2.0-dev:i386
-        echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y libffi-dev libffi-dev:i386
-
-        # echo_run sudo apt-get install --no-install-recommends --allow-downgrades -y \
-        #     libcurl4-openssl-dev libcurl4-openssl-dev:i386 libgc-dev libgc-dev:i386 \
-        #     libsdl1.2-dev libsdl1.2-dev:i386 libsfml-dev libsfml-dev:i386 libglib2.0-dev libglib2.0-dev:i386 libffi-dev libffi-dev:i386
-
-        #DEBIAN_FRONTEND='noninteractive' \
-        #  echo_run sudo apt-fast install --no-install-recommends --allow-downgrades -yq \
-        #    g++-multilib gcc-multilib libcurl4-openssl-dev:i386 libgc-dev:i386 \
-        #    libsdl1.2-dev:i386 libsfml-dev:i386 libglib2.0-dev:i386 libffi-dev:i386
+        DEBIAN_FRONTEND='noninteractive' \
+          echo_run sudo apt-fast install --no-install-recommends --allow-downgrades -yq \
+            g++-multilib gcc-multilib libcurl4-openssl-dev:i386 libgc-dev:i386 \
+            libsdl1.2-dev:i386 libsfml-dev:i386 libglib2.0-dev:i386 libffi-dev:i386
 
         cat << EOF > bin/gcc
         #!/bin/bash
